# Default values for env-injector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry.revsys.com/nuremberg
  pullPolicy: IfNotPresent
  tag: 0.0.0

Plug: hlsnp

deploymentEnvironment: prod

imagePullSecret: revsys-docker-registry

publicFqdn: nuremberg.revsys.dev

nameOverride: ""

fullnameOverride: hlsnp

replicaCount: 1

initCommands:
  - name: migrate
    command: './manage.py migrate --noinput'
  - name: collectstatic
    command: './manage.py collectstatic --noinput'

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 256Mi


