# Generated by Django 4.1.2 on 2022-10-07 20:46

from django.db import migrations, models
import nuremberg.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0006_transcript_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptpage',
            name='image_url',
            field=models.TextField(blank=True, db_column='image_url', null=True),
        ),
        migrations.RenameField(
            model_name='transcriptpage',
            old_name='image_url',
            new_name='_url',
        ),
        migrations.AddField(
            model_name='transcriptpage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=nuremberg.core.storages.TranscriptStorage()),
        ),
    ]
