# Generated by Django 4.1.2 on 2023-01-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0007_alter_transcriptpage_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptpage',
            name='_url',
        ),
    ]
