# Generated by Django 4.1.7 on 2025-11-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0008_remove_transcriptpage__url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptpage',
            name='page_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcriptpage',
            name='seq_number',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transcriptpage',
            name='volume_seq_number',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
