# Generated by Django 4.1.7 on 2025-11-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0009_alter_transcriptpage_page_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptvolume',
            name='volume_number',
            field=models.BigIntegerField(),
        ),
    ]
