
version: '2'
services:

  solr:
    image: registry.revsys.com/nuremberg:last-solr
    volumes: []

  web:
    image: registry.revsys.com/nuremberg:v0.2.7-test
    volumes: []
    volumes:
      - $PWD/tmp:/mnt
    environment:
      - SOLR_URL=http://solr:8983/solr/nuremberg_dev


volumes: {}

