apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.Plug}}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Values.Plug}}
    env: {{.Values.deploymentEnvironment}}
    heritage: {{.Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    revision: {{ .Release.Revision | default 0 | quote }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
spec:
  replicas: {{.Values.replicaCount | int}}
  selector:
    matchLabels:
      app: {{.Values.Plug}}
      env: {{.Values.deploymentEnvironment}}
  template:
    metadata:
      labels:
        app: {{.Values.Plug}}
        env: {{.Values.deploymentEnvironment}}
{{- include "InitAnnotation" . | indent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
{{- include "InitSpec" . | indent 6 }}
{{ if .Values.tolerations -}}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
      imagePullSecrets:
        - name: {{.Values.imagePullSecret | quote}}
      containers:
        -
          name: main
          image: {{.Values.image.repository}}:{{.Chart.AppVersion}}
          command: ["/.venv/bin/gunicorn"]
          args:
            - --bind=:8000
            - nuremberg.wsgi
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}
          envFrom:
            -
              configMapRef:
                name: {{.Values.Plug}}-env
            -
              secretRef:
                name: {{.Values.Plug}}-env
          ports:
            -
              protocol: TCP
              containerPort: 8000
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
