# vim: ft=yaml nolist

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.Plug}}
  namespace: {{.Release.Namespace}}
  labels:
    env: {{.Values.deploymentEnvironment}}
    heritage: {{.Release.Service | quote }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.publicFqdn }}
    secretName: {{.Values.publicFqdn}}-tls
  rules:
  -
    host: {{ .Values.publicFqdn }}
    http:
      paths:
      -
        path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{.Values.Plug}}
            port:
              number: 80
