# vim: ft=yaml nolist

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.Plug}}
  namespace: {{.Release.Namespace}}
  labels:
    env: {{.Values.deploymentEnvironment}}
    heritage: {{.Release.Service | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/denylist-source-range: "43.146.0.0/15,43.148.0.0/14,43.153.0.0/18,43.176.0.0/12,103.95.224.0/22,114.117.144.0/20,142.70.0.0/16,142.86.0.0/16,149.41.0.0/16,150.248.0.0/16,158.79.0.0/24"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.publicFqdn }}
    - nuremberg.law.harvard.edu
    secretName: {{.Values.publicFqdn}}-tls
  rules:
  -
    host: {{ .Values.publicFqdn }}
    http:
      paths:
      -
        path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{.Values.Plug}}
            port:
              number: 80

  -
    host: nuremberg.law.harvard.edu
    http:
      paths:
      -
        path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{.Values.Plug}}
            port:
              number: 80
