apiVersion: v1
kind: Service
metadata:
  name: {{.Values.Plug}}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Values.Plug}}
    env: {{.Values.deploymentEnvironment}}
    heritage: {{.Release.Service | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
    -
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: {{.Values.Plug}}
    env: {{.Values.deploymentEnvironment}}
