from django.urls import path

from .views import ContentView, LandingView, ReportDetailView, TrialsView

app_name = 'content'
urlpatterns = [
    path(
        '',
        LandingView.as_view(),
        name="landing",
    ),
    path(
        'nuremberg/php/docs_swi.php',
        LandingView.as_view(),
        name="landing",
    ),
    path(
        'trials',
        TrialsView.as_view(),
        name="trials",
    ),
    path(
        'approaches',
        ContentView.as_view(template_name='content/approaches.html'),
        name="approaches",
    ),
    path(
        'history',
        ContentView.as_view(template_name='content/history.html'),
        name="history",
    ),
    path(
        'about',
        ContentView.as_view(template_name='content/about.html'),
        name="about",
    ),
    path(
        'people',
        ContentView.as_view(template_name='content/people.html'),
        name="people",
    ),
    path(
        'intro',
        ContentView.as_view(template_name='content/about.html'),
        name="intro",
    ),
    path(
        'funding',
        ContentView.as_view(template_name='content/funding.html'),
        name="funding",
    ),
    path(
        'additional',
        ContentView.as_view(template_name='content/history.html'),
        name="additional",
    ),
    path(
        'documents',
        ContentView.as_view(template_name='content/documents.html'),
        name="documents",
    ),
    path(
        'imt_intro',
        ContentView.as_view(template_name='content/imt_intro.html'),
        name="imt",
    ),
    path(
        'nmt_1_intro',
        ContentView.as_view(template_name='content/nmt_1_intro.html'),
        name="nmt-1",
    ),
    path(
        'nmt_2_intro',
        ContentView.as_view(template_name='content/nmt_2_intro.html'),
        name="nmt-2",
    ),
    path(
        'nmt_3_intro',
        ContentView.as_view(template_name='content/nmt_3_intro.html'),
        name="nmt-3",
    ),
    path(
        'nmt_4_intro',
        ContentView.as_view(template_name='content/nmt_4_intro.html'),
        name="nmt-4",
    ),
    path(
        'nmt_7_intro',
        ContentView.as_view(template_name='content/nmt_7_intro.html'),
        name="nmt-7",
    ),
    path(
        'nmt_9_intro',
        ContentView.as_view(template_name='content/nmt_9_intro.html'),
        name="nmt-9",
    ),
    path('reports/<int:pk>', ReportDetailView.as_view(), name='report-detail'),
]
