# Generated by Django 4.1.2 on 2022-10-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.AutoField(db_column='RecordID', primary_key=True, serialize=False)),
                ('inscription', models.CharField(db_column='Inscription', max_length=2000)),
                ('year_taken', models.CharField(blank=True, db_column='Date', max_length=100, null=True)),
                ('image_url', models.CharField(db_column='FullImageURL', max_length=100, unique=True)),
                ('thumb_url', models.CharField(db_column='ThumbnailURL', max_length=100)),
                ('material_type', models.CharField(db_column='MaterialType', max_length=100)),
                ('via_id', models.CharField(blank=True, db_column='LocalSystemID', max_length=200, null=True)),
                ('created_at', models.DateTimeField(db_column='RecordCreated')),
            ],
            options={
                'db_table': 'tblPhotographs',
                'managed': False,
            },
        ),
    ]
