# Generated by Django 4.1.2 on 2022-11-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_personalauthorproperty_personalauthorpropertyrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentText',
            fields=[
                ('id', models.AutoField(db_column='RecordID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=1000)),
                ('evidence_code_tag', models.CharField(db_column='DocID', max_length=100)),
                ('evidence_code_series', models.CharField(db_column='DocCodeSeries', max_length=100)),
                ('evidence_code_num', models.CharField(db_column='DocCodeNum', max_length=100)),
                ('source_citation', models.CharField(db_column='SourceCitation', max_length=500)),
                ('load_timestamp', models.DateTimeField(db_column='LoadDateTime')),
                ('text', models.TextField(blank=True, db_column='DocText', null=True)),
            ],
            options={
                'db_table': 'tblNurembergDocTexts',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='documentactivity',
            options={'managed': False, 'verbose_name_plural': 'Document activities'},
        ),
    ]
