# Generated by Django 4.1.2 on 2022-11-15 18:49

from django.db import migrations, models
import django.db.models.deletion
import nuremberg.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documenttext_alter_documentactivity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAuthorExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, storage=nuremberg.core.storages.AuthorStorage(), upload_to='')),
                ('image_alt', models.CharField(max_length=1024)),
                ('properties', models.JSONField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='documents.documentpersonalauthor')),
            ],
        ),
    ]
