# Generated by Django 4.1.2 on 2022-12-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_documentauthorextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCitation',
            fields=[
                ('id', models.AutoField(db_column='CasesDatesListID', primary_key=True, serialize=False)),
                ('day', models.IntegerField(db_column='CaseDay')),
                ('month', models.IntegerField(db_column='CaseMonthID')),
                ('year', models.IntegerField(db_column='CaseYear')),
                ('transcript_page_number', models.IntegerField(db_column='EngTransPageNo')),
                ('transcript_page_number_suffix', models.TextField(db_column='EngTransPageNoSuffix', null=True)),
            ],
            options={
                'db_table': 'tblCasesDatesList',
                'managed': False,
            },
        ),
    ]
