# Generated by Django 4.1.2 on 2022-12-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_documentcitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentExternalMetadata',
            fields=[
                ('id', models.AutoField(db_column='RecordID', primary_key=True, serialize=False)),
                ('summary', models.CharField(db_column='DocSummary', max_length=1000)),
                ('evidence_code_series', models.CharField(db_column='EFSeries', max_length=10)),
                ('evidence_code_num', models.CharField(db_column='EFCodeNum', max_length=10)),
                ('evidence_code_suffix', models.CharField(db_column='EFCodeNumSuffix', max_length=10)),
                ('exhibit_case', models.CharField(db_column='ExhibitCase', max_length=10)),
                ('exhibit_country', models.CharField(db_column='ExhibitCountry', max_length=100)),
                ('exhibit_side', models.CharField(db_column='ExhibitSide', max_length=100)),
                ('exhibit_defendant', models.CharField(db_column='ExhibitDefendant', max_length=100)),
                ('exhibit_num', models.CharField(db_column='ExhibitNum', max_length=10)),
                ('updated_at', models.DateTimeField(db_column='RecordUpdated')),
            ],
            options={
                'db_table': 'tblDocExternalMetadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentExternalMetadataSource',
            fields=[
                ('id', models.AutoField(db_column='SourceID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='SourceLabel', max_length=300)),
                ('description', models.TextField(db_column='Source')),
            ],
            options={
                'db_table': 'tblDocExternalMetadataSources',
                'managed': False,
            },
        ),
    ]
