# Generated by Django 4.1.2 on 2022-12-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_documentexternalmetadata_and_source'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documenttext',
            table='tblNurembergFullTexts',
        ),
    ]
