# Generated by Django 4.1.2 on 2023-01-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_documenttext_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentimage',
            name='_url',
        ),
        migrations.RemoveField(
            model_name='documentimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='documentimage',
            name='width',
        ),
    ]
