# Generated by Django 4.1.2 on 2023-01-10 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_remove_documentimage__url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='image_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.documentimagetype'),
        ),
    ]
