# Generated by Django 4.1.2 on 2023-02-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_alter_documentimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentauthorextra',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
