# Generated by Django 4.1.2 on 2023-02-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_documentauthorextra_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseDocumentBookCodeName',
            fields=[
                ('id', models.AutoField(db_column='DefenseDocBkNameID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='DefenseDocBkName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblDefenseDocBkNames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefenseDocumentCodeName',
            fields=[
                ('id', models.AutoField(db_column='DefenseDocNameID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='DefenseDocName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblDefenseDocNames',
                'managed': False,
            },
        ),
    ]
