# Generated by Django 4.1.2 on 2023-01-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystReport',
            fields=[
                ('id', models.AutoField(db_column='RecordID', primary_key=True, serialize=False)),
                ('analyst', models.CharField(db_column='Analyst', max_length=100)),
                ('date', models.DateField(db_column='DateSort')),
                ('date_display', models.CharField(db_column='DateDisplay', max_length=100)),
                ('report', models.CharField(db_column='Report', max_length=15000)),
            ],
            options={
                'db_table': 'tblDocAnalystReports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrialInfo',
            fields=[
                ('id', models.AutoField(db_column='RecordID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='TrialName', max_length=200)),
                ('alias', models.CharField(db_column='TrialNameAlias', max_length=200)),
                ('description', models.TextField(db_column='Description')),
            ],
            options={
                'db_table': 'tblTrialsInfo',
                'managed': False,
            },
        ),
    ]
