# Generated by Django 4.1.2 on 2023-01-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrialInfo',
        ),
        migrations.AlterModelOptions(
            name='analystreport',
            options={'managed': False, 'ordering': ['-date']},
        ),
    ]
