name: Test

# on:
#   workflow_dispatch:
#   push: []

jobs:
  build-test-image:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 4
      fail-fast: false

    needs:
      - Build-Test-Image

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: update docker-compose
          run: |
            mkdir -pv $HOME/.docker/cli-plugins
            curl -Ls -o $HOME/.docker/cli-plugins/docker-compose https://github.com/docker/compose/releases/download/v2.13.0/docker-compose-linux-x86_64
            chmod 755 $HOME/.docker/cli-plugins/docker-compose
            ln -sfv $HOME/.docker/cli-plugins/docker-compose $( which docker-compose )
        - uses: extractions/setup-just@v1
          with:
            just-version: '1.9.0'
        - name: Login to REVSYS Container Registry
          uses: docker/login-action@v2
          with:
            registry: registry.revsys.com
            username: github
            password: ${{ secrets.REVSYS_DOCKER_REGISTRY_PASSWORD }}
        - name: Current Version
          run: just version | tee -a $GITHUB_OUTPUT
        - name: Run tests
          run: just test
        - name: Get logs on failure
          run: just ci-dc logs
          if: failure()
