#1
name: Build-Test-Image

on:
  workflow_dispatch:
  push:
    branches:
      - ci--setup-job-run-specs

  pull_request:
    types:
      - closed
    branches:
      - ci--setup-job-run-specs

jobs:
  build-test-image:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 4
      fail-fast: false

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - uses: extractions/setup-just@v1
          with:
            just-version: '1.9.0'
        - name: Login to REVSYS Container Registry
          uses: docker/login-action@v2
          with:
            registry: registry.revsys.com
            username: github
            password: ${{ secrets.REVSYS_DOCKER_REGISTRY_PASSWORD }}
        - name: Current Version
          run: echo "Current Version: $( just version )" >> $GITHUB_OUTPUT
        - name: Build test runner
          run: just push tester
