name: increment version particle

on:
  workflow_call:
    inputs:
      level:
        description: bumpversion level (major, minor, patch, build[default])
        required: true
        default: build
        type: choice
        options:
          - major
          - minor
          - patch
          - build
    outputs:
      previous:
        value: ${{ jobs.bumpversion.outputs.original }}
      current:
        value: ${{ jobs.bumpversion.outputs.current }}


jobs:

  bumpversion:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 4
      fail-fast: false

    steps:
        - name: Checkout code
          #uses: actions/checkout@v3
          uses: gladiatr72/checkout-action@v3-no-noise
        - uses: extractions/setup-just@v1
          with:
            just-version: '1.9.0'
        - name: update docker-compose
          run: |
            mkdir -pv $HOME/.docker/cli-plugins
            curl -Ls -o $HOME/.docker/cli-plugins/docker-compose https://github.com/docker/compose/releases/download/v2.13.0/docker-compose-linux-x86_64
            chmod 755 $HOME/.docker/cli-plugins/docker-compose
            ln -sfv $HOME/.docker/cli-plugins/docker-compose $( which docker-compose )
        - name: Login to REVSYS Container Registry
          uses: docker/login-action@v2
          with:
            registry: registry.revsys.com
            username: github
            password: ${{ secrets.REVSYS_DOCKER_REGISTRY_PASSWORD }}
        - name: Current Version
          run: just banner version && echo "previous=$( just version )" >> $GITHUB_OUTPUT
        - name: Run
          run: just bump ${{ inputs.level }}
        - name: New Version
          run: just banner version && echo "current=$( just version )" >> $GITHUB_OUTPUT
        - name: push new version commits (no tags)
          run: git push
