name: nuremberg-ci

on:
#    push:
#      branches:
#        - ci--setup-job-run-specs
  workflow_dispatch:

  push:
    branches:
      - ci--*

  pull_request:
    branches:
      - ci--*
    types:
      - opened
      - reopened
      - synchronize
      - closed


concurrency:
  group: ci-tests-${{ github.event.pull_request.head.ref }}-1
  cancel-in-progress: true

jobs:

  setup:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 8
      fail-fast: true


    steps:
        - name: Login to REVSYS Container Registry
          uses: docker/login-action@v2
          with:
            registry: registry.revsys.com
            username: github
            password: ${{ secrets.REVSYS_DOCKER_REGISTRY_PASSWORD }}
        - name: install just
          run: |
            docker run -v /home/runner/.local/bin:/dist registry.revsys.com/just:0.9.4 || just --version
        - name: Checkout code
          uses: gladiatr72/checkout-action@v3-no-noise
          with:
            ref: ${{ github.event.pull_request.head.ref }}
        - name: update docker-compose
          run: |
            mkdir -pv $HOME/.docker/cli-plugins
            curl -Ls -o $HOME/.docker/cli-plugins/docker-compose \
              https://github.com/docker/compose/releases/download/v2.13.0/docker-compose-linux-x86_64
            chmod 755 $HOME/.docker/cli-plugins/docker-compose
            ln -sfv $HOME/.docker/cli-plugins/docker-compose $( which docker-compose )
        - name: version
          run: just banner version
        - if: github.event.action == 'opened'
          name: new PR bump (build)
          run: just bump build
        - if: github.event.pull_request.merged == true
          name: merged PR bump (patch)
          run: just bump patch
        - name: new version
          if: github.event.action == 'opened' || github.event.pull_request.merged == true
          run: just banner version
        #- run: just build tester --load verbosity=1
        #- run: just test
        - if: github.event.pull_request.merged == true
          run: git push --tags
        - run: git push
