name: nuremberg-ci

on:
#    push:
#      branches:
#        - ci--setup-job-run-specs
  workflow_dispatch:

  pull_request:
    branches: 
      - ci--*
    types:
      - opened
      - closed


jobs:

  setup:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 4
      fail-fast: false

    steps:
        - name: Checkout code
          #uses: actions/checkout@v3
          uses: gladiatr72/checkout-action@v3-no-noise
        - uses: extractions/setup-just@v1
          with:
            just-version: '1.9.0'
        - name: update docker-compose
          run: |
            mkdir -pv $HOME/.docker/cli-plugins
            curl -Ls -o $HOME/.docker/cli-plugins/docker-compose \
              https://github.com/docker/compose/releases/download/v2.13.0/docker-compose-linux-x86_64
            chmod 755 $HOME/.docker/cli-plugins/docker-compose
            ln -sfv $HOME/.docker/cli-plugins/docker-compose $( which docker-compose )
        - name: Login to REVSYS Container Registry
          uses: docker/login-action@v2
          with:
            registry: registry.revsys.com
            username: github
            password: ${{ secrets.REVSYS_DOCKER_REGISTRY_PASSWORD }}

  bumpversion-new-pr:
    if: github.event.action == 'opened'
    uses: ./.github/workflows/bumpversion.yml
    needs: [setup]
    with:
      level: build

  bumpversion-merged:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/bumpversion.yml
    needs: [setup]
    with:
        level: patch


  lets-see:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 4
      fail-fast: false

    steps:
      - run: echo ${{ toJson(github.event.action) }}
#   lets-see:
#     steps
#     run: |
#       #!/usr/bin/env bash
#       echo "previous = ${{ needs.bumpversion-new-pr.outputs.previous }}"
#       echo -en "current = "
#       [[ -n "${{ needs.bumpversion-new-pr.outputs.current }}" ]] \
#        && echo "${{ needs.bumpversion-new-pr.outputs.current }}"
#       [[ -n "${{ needs.bumpversion-merged.outputs.current }}" ]] \
#        && echo "${{ needs.bumpversion-merged.outputs.current }}"
# 
