name: Push to Main

on:
  push:
  workflow_dispatch:


concurrency:
  group: ci-push-to-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  contexts:
    runs-on: ubuntu-latest
    steps:
      -
        name: github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"


  solr:
    runs-on: ubuntu-latest

    outputs:
      change-detected: ${{ steps.check-dumps.outputs.change-detected }}

    steps:
      -
        name: check for new dump
        id: check-dumps
        run: |
          lastUpdate=$( git log -1 --format=%H HEAD^ -- dumps/nuremberg_prod_dump_latest.sqlite3.zip )
          [[ -n "${lastUpdate}" ]] && ( \
            [[ "${{ github.ref }}" == "${lastUpdate}" ]] && \
              echo "change-detected=true" >> $GITHUB_OUTPUT || \
              echo "change-detected=false" >> $GITHUB_OUTPUT \
          ) || echo "change-detected=true" >> $GITHUB_OUTPUT

  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: true

    needs:
      - solr

    env:
      probablyPr: "${{ contains(github.event.commits.*.committer.name, 'GitHub') && ( github.ref_name == 'main' && github.ref_type == 'branch' ) }}"
      probablyNotPr: "${{ ! contains(github.event.committs.*.committer.name, 'GitHub') && (github.ref_name == 'main' && github.ref_type == 'branch' ) }}"

    steps:
      -
        name: Login to REVSYS Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.revsys.com
          username: github
          password: ${{ secrets.REVSYS_DOCKER_REGISTRY_PASSWORD }}
      -
        name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      -
        name: install just
        run: |
          docker run -v /home/runner/.local/bin:/dist registry.revsys.com/just:0.9.4 || just --version
      -
        name: Checkout code
        uses: gladiatr72/checkout-action@v3-no-noise
        with:
          ref: ${{ github.ref_name }}
      -
        name: initial version
        run: |
          just banner version
          echo "### Version: $( just version )" >> $GITHUB_STEP_SUMMARY
          echo "::notice::$( just version )"
      -
        name: bump version (pr merge)
        if: ${{ env.probablyPr }}
        run: |
          just bump patch && \
          echo "### Version Update: $( just version )" >> $GITHUB_STEP_SUMMARY
          echo "::notice::$( just version )"
      -
        name: bump version (direct commit)
        if: ${{ env.probablyNotPr }}
        run: |
          just bump build && \
          echo "### Version Update: $( just version )" >> $GITHUB_STEP_SUMMARY
          echo "::notice::$( just version )"
      -
        name: build test image
        run: just build tester
#      -
#        name: run tests
#        run: just test
      -
        name: push version updates to repo
        if: ${{ github.ref_type == branch && github.ref_name == main }}
        run: |
          git push && \
          git push --tags
      -
        name: push docker image to registry
        if: ${{ github.ref_type == branch && github.ref_name == main }}
        run: just push
      -
        name: deploy to dev
        if: ${{ github.ref_type == branch && github.ref_name == main }}
        run: just deploy


