name: Test
on: [workflow_call]

jobs:
  run-tests:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 4
      fail-fast: false

    steps:
        - name: Current Version
          run: just version | tee -a $GITHUB_OUTPUT
        - name: Run tests
          run: just test
        - name: Get logs on failure
          run: just ci-dc logs
          if: failure()
