name: Push-Release-Image

on:
  workflow_dispatch:

  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 4
      fail-fast: false

    needs:
      - Test

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - uses: extractions/setup-just@v1
          with:
            just-version: '1.9.0'
        - name: Login to REVSYS Container Registry
          uses: docker/login-action@v2
          with:
            registry: registry.revsys.com
            username: github
            password: ${{ secrets.REVSYS_DOCKER_REGISTRY_PASSWORD }}
        - name: Current Version
          run: just version >> $GITHUB_OUTPUT
        - name: Push Release Image
          run: just push release
