name: Run Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 4
      fail-fast: false

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: update docker-compose
          run: |
            mkdir -pv $HOME/.docker/cli-plugins
            curl -Ls -o $HOME/.docker/cli-plugins/docker-compose https://github.com/docker/compose/releases/download/v2.13.0/docker-compose-linux-x86_64
            chmod 755 $HOME/.docker/cli-plugins/docker-compose
            ln -sfv $HOME/.docker/cli-plugins/docker-compose $( which docker-compose )
        - name: Login to REVSYS Container Registry
          uses: docker/login-action@v2
          with:
            registry: registry.revsys.com
            username: github
            password: ${{ secrets.REVSYS_DOCKER_REGISTRY_PASSWORD }}
        - name: Invoke docker compose
          run: docker-compose -f ./docker-compose.yml -f docker-compose.override.yml -f ./docker-compose.solr-last.yml up -d

        - name: Setup data storages
          env:
            SOLR_RESTORE: ""
          run: bash init.sh

        - name: Run unit tests
          run: docker compose exec -T web pytest

        - name: Run browser tests
          run: docker compose exec -T web pytest --no-cov nuremberg/documents/browser_tests.py

        - name: Get logs on failure
          run: docker compose logs
          if: failure()

        - name: Run pre-commit to check code style (no commits will be made)
          uses: pre-commit/action@v3.0.0

        - name: Down images
          run: docker compose down
          if: always()
