name: Run Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 4
      fail-fast: false

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: update docker-compose
          run: |
            mkdir -pv $HOME/.docker/cli-plugins
            curl -Ls -o $HOME/.docker/cli-plugins/docker-compose https://github.com/docker/compose/releases/download/v2.13.0/docker-compose-linux-x86_64
            chmod 755 $HOME/.docker/cli-plugins/docker-compose
            ln -sfv $HOME/.docker/cli-plugins/docker-compose $( which docker-compose )
        - uses: extractions/setup-just@v1
          with:
            just-version: '1.9.0'
        - name: Login to REVSYS Container Registry
          uses: docker/login-action@v2
          with:
            registry: registry.revsys.com
            username: github
            password: ${{ secrets.REVSYS_DOCKER_REGISTRY_PASSWORD }}
        - name: Build unit test runners
          run: |
            just build tester
            just build browser-tester
        - name: Tests
          run: just test
        - name: Get logs on failure
          run: docker compose logs
          if: failure()

        - name: Run pre-commit to check code style (no commits will be made)
          uses: pre-commit/action@v3.0.0

        - name: Down images
          run: docker compose down
          if: always()
